package ee.taltech.iti0202.bookscraper.models;

public enum BookGenre {
    HISTORY, COMPUTERS_AND_INTERNET, ASTROLOGY_AND_SORCERY,
    ARCHITECTURE_AND_INTERIOR_DESIGN, BIOGRAPHY_AND_MEMOIRS, ABOUT_ESTONIA,
    THE_HUMANITIES, FICTION, ECONOMICS_AND_LAW, TEXTBOOKS_AND_EDUCATION,
    LANGUAGES_AND_DICTIONARIES, HOUSE_AND_GARDEN, COOKING,
    ART_AND_MUSIC, THEATRE_AND_CINEMA, CHILDREN_LITERATURE,
    YOUNG_ADULT, NATURAL_SCIENCES, ENTERTAINMENT,
    PSYCHOLOGY, TRAVELLING_AND_TOURISM, RELIGION_AND_MYTHOLOGY,
    RELATIONSHIPS_AND_FAMILY, REFERENCE_BOOKS, HEALTH, SOCIETY_AND_POLITICS,
    UNKNOWN_GENRE
}
